@startuml arcitecture
component core {
	package core.core
}

component persistence {
	package persistence.filesaving
}

component com.google.Gson{
}

persistence ..> com.google.Gson
persistence ..> core

component ui{
	package ui.ui
}
component org.openjfx {
	component javafx-fxml {
	}
	component javafx-controls{
	}
}
component org.mockito

ui ..> core
ui ..> persistence
ui ..> org.openjfx
ui ..> org.mockito


component springboot {
	package financevision.springboot.restserver
}

component org.springframework

springboot ..> org.springframework
springboot ..> persistence
springboot ..> core


@enduml